### ISSUE TITLE
How do i install that extension to FreeCad?

### ISSUE THREAD

**Issue by christoph-buente** [wood-galaxy/FreeCAD-Timber#1]

**Comment by luzpaz** [comment]
you can install via https://github.com/FreeCAD/FreeCAD-addons#installing

**Comment by luzpaz** [comment]
@wood-galaxy i think you can close this ticket
though you may want to mention the ability to install via the FC addon-manager on the README

**Comment by luzpaz** [comment]
@wood-galaxy please close ticket

**Comment by luzpaz** [comment]
@wood-galaxy ping

**Comment by j-wiedemann** [comment]
added in readme
thanks @luzpaz
