### ISSUE TITLE
Please add README description + install instructions + screenshots

### ISSUE THREAD

**Issue by luzpaz** [wood-galaxy/FreeCAD-Timber#2]
Also add the freecad forum announcement thread: https://forum.freecadweb.org/viewtopic.php?t=12559

**Comment by luzpaz** [comment]
@wood-galaxy please ack

**Comment by j-wiedemann** [comment]
I will make some cleaning and post on forum announcement thread

**Comment by luzpaz** [comment]
![image](https://user-images.githubusercontent.com/4140247/59509848-3228bf00-8e80-11e9-8be9-aa457fde7e63.png)
