### ISSUE TITLE
Updating Timber WB to be compatible with the upcoming 0.18 release (req. py3 and Qt5 compatibility)

### ISSUE THREAD

**Issue by luzpaz** [wood-galaxy/FreeCAD-Timber#4]
ref: https://github.com/FreeCAD/FreeCAD-addons/issues/93

**Comment by luzpaz** [comment]
@wood-galaxy please follow-up

**Comment by j-wiedemann** [comment]
HI @luzpaz , thanks for the link I will do that asap

**Comment by baruch-eliezer** [comment]
Do you have a projected completion date for the Timber WB to be compatible with the upcoming 0.18 release?

I have started working on learning your code to incorporate Japanese Architectural Elements and Joinery to the WB.

**Comment by luzpaz** [comment]
@baruch-eliezer neat!

**Comment by luzpaz** [comment]
https://github.com/wood-galaxy/FreeCAD-Timber#important-note :cry:
