### ISSUE TITLE
What is the logo that represents this WB?

### ISSUE THREAD

**Issue by luzpaz** [wood-galaxy/FreeCAD-Timber#5]
I noticed that it's possible to see it in: 
![image](https://www.freecadweb.org/wiki/images/4/40/Timber-menu-orizz.png)

But it looks like it's an XPM.

**Comment by j-wiedemann** [comment]
The logo is a wood frame.
![timberframe](https://user-images.githubusercontent.com/4691535/46323768-3661c480-c5f0-11e8-95c7-461719662c14.jpeg)

**Comment by luzpaz** [comment]
Awesome logo, is there a 32px size we can add to https://www.freecadweb.org/wiki/Template:DevWorkbenches ?

**Comment by j-wiedemann** [comment]
[TimberFrame.svg.gz](https://github.com/wood-galaxy/FreeCAD-Timber/files/2436231/TimberFrame.svg.gz)
I've just redone it. Just extract the gz archive to find a svg file.
